# const 사용 하는 이유는 런타임 시 const가 붙어있으면 생략하고 컴파일시에 생성되기 때문에 런타임이 빠르게 돌고 가벼워진다.
#required 에러를 설정하지 않으면 기본적으로는 required가 되어있어도 에러 체크를 해주지않는다.

include: package:pedantic/analysis_options.yaml
analyzer:
  errors:
    prefer_const_declarations: error
    prefer_const_constructors: error
    missing_required_param: error
linter:
  rules:
    prefer_const_declarations: true
    prefer_const_constructors: true
    missing_required_param: true
    #pedantic을 사용하면 구글에서 사용하는 룰을 동일하게사용 가능하다.

